name: DeepTrace CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  python-check:
    name: Python Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mediapipe opencv-python numpy datasets

      - name: Check Python files
        run: |
          python -m py_compile dataset/test_landmarks.py
          python -m py_compile dataset/visualize_landmarks.py
          python -m py_compile dataset/extract_geometry.py
          python -m py_compile dataset/extract_features.py


  backend-check:
    name: Backend Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Check backend syntax
        working-directory: backend
        run: node --check server.js


  frontend-check:
    name: Frontend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build